site_name: CHI

pages:
    - Home: index.md
    - About: 
      - a:
        - 'HI1' : 1.md
        - 'HI2' : 1.md
        - 'HI3' : 1.md
      - b:
        - 'HI4' : 1.md
        - 'HI5' : 1.md
theme: journal